import type { Metadata } from "next";
import localFont from "next/font/local";
import { cn } from "@/lib/utils.ts";
import "./globals.css";

const fontBrandRegular = localFont({
  src: "./fonts/borna-regular-webfont.woff2",
  variable: "--font-brand-regular",
  weight: "500",
});
const fontBrandSemi = localFont({
  src: "./fonts/borna-semibold-webfont.woff2",
  variable: "--font-brand-semi",
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body className={` ${fontBrandRegular.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
